<a href="https://colab.research.google.com/github/axccun/TensorFlow/blob/main/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [27]:
mnist = tf.keras.datasets.mnist

In [28]:
mnist

<module 'keras.api.datasets.mnist' from '/usr/local/lib/python3.11/dist-packages/keras/api/datasets/mnist/__init__.py'>

In [29]:
data = mnist.load_data()
print(type(data))
len(data)

<class 'tuple'>


2

In [30]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [31]:
x_train,x_test = x_train/255.0,x_test/255.0

In [32]:
model = tf.keras.Sequential([
    tf.keras.Input(shape = (28,28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [33]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.22098997,  0.00632696,  0.6675994 , -0.3289283 ,  0.352352  ,
        -0.48513353, -0.66684455,  0.37344578,  0.88349736,  0.20840886]],
      dtype=float32)

In [34]:
tf.nn.softmax(predictions).numpy()

array([[0.06608096, 0.08294664, 0.16068885, 0.05931974, 0.11723994,
        0.05074114, 0.04231011, 0.11973923, 0.19941097, 0.10152239]],
      dtype=float32)

In [35]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [37]:
loss_fn(y_train[:1],predictions).numpy()

np.float32(2.9810183)

In [38]:
model.compile(optimizer='adam',loss = loss_fn ,metrics = ['accuracy'])

In [40]:
model.fit(x_train,y_train,epochs = 6)

Epoch 1/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9131 - loss: 0.3025
Epoch 2/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9569 - loss: 0.1495
Epoch 3/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9683 - loss: 0.1095
Epoch 4/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9719 - loss: 0.0880
Epoch 5/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9755 - loss: 0.0760
Epoch 6/6
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9787 - loss: 0.0652


In [41]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9790 - loss: 0.0679


[0.06785459071397781, 0.9789999723434448]

In [42]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [43]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8151484e-08, 1.6892335e-09, 3.7041335e-07, 4.0951316e-05,
        1.6177282e-11, 2.0772390e-08, 3.8753668e-14, 9.9994171e-01,
        6.4072253e-08, 1.6907117e-05],
       [5.4747307e-11, 3.2912500e-05, 9.9994004e-01, 2.7033611e-05,
        1.2476527e-17, 4.3857472e-08, 4.4910447e-12, 1.6837355e-14,
        3.7209835e-09, 8.1512894e-15],
       [6.3149025e-07, 9.9831843e-01, 3.4308672e-04, 3.5161552e-06,
        9.4512121e-05, 3.3181859e-06, 2.4926750e-05, 1.0788112e-03,
        1.3184237e-04, 8.2143151e-07],
       [9.9996066e-01, 1.7307357e-11, 2.9304845e-05, 8.8894057e-09,
        3.6156486e-08, 4.3345159e-07, 8.7595129e-07, 8.4816147e-06,
        5.0770921e-09, 2.1852863e-07],
       [1.7604617e-06, 1.2607456e-08, 1.8486784e-06, 7.0298498e-08,
        9.8880857e-01, 8.1858529e-09, 1.6447882e-06, 6.8882058e-05,
        1.5990504e-07, 1.1117033e-02]], dtype=float32)>